// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account.proto

#include "account.pb.h"
#include "account.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace example {

static const char* LoginService_method_names[] = {
  "/example.LoginService/Login",
};

std::unique_ptr< LoginService::Stub> LoginService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LoginService::Stub> stub(new LoginService::Stub(channel, options));
  return stub;
}

LoginService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(LoginService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LoginService::Stub::Login(::grpc::ClientContext* context, const ::example::LoginRequest& request, ::example::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::example::LoginRequest, ::example::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void LoginService::Stub::async::Login(::grpc::ClientContext* context, const ::example::LoginRequest* request, ::example::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::example::LoginRequest, ::example::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void LoginService::Stub::async::Login(::grpc::ClientContext* context, const ::example::LoginRequest* request, ::example::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::example::LoginResponse>* LoginService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::example::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::example::LoginResponse, ::example::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::example::LoginResponse>* LoginService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::example::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

LoginService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LoginService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LoginService::Service, ::example::LoginRequest, ::example::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LoginService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::example::LoginRequest* req,
             ::example::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

LoginService::Service::~Service() {
}

::grpc::Status LoginService::Service::Login(::grpc::ServerContext* context, const ::example::LoginRequest* request, ::example::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace example

